language: python

matrix:
  include:
    - python: 3.4
      env:
        - COVERAGE=false
    - python: 3.5
      env:
        - COVERAGE=false

    - python: 3.6
      env:
        - COVERAGE=true

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda config --set always_yes true
  - conda config --add channels conda-forge
  - conda update conda
  - conda install nomkl

install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION --channel=conda-forge
  - source activate test
  - conda install --yes numpy matplotlib scipy --channel=conda-forge
  - conda install --yes pytest coverage pytest-cov pytest-pep8 coveralls --channel=conda-forge
  - pip install .

script:
  - python check_watershed.py --verbose --pep8

after_success:
  - if [ ${COVERAGE} = true ]; then
      coverage run --source watershed check_watershed.py;
      coverage report -m;
      coveralls;
    fi


